# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 09:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=300)),
                ('issueDate', models.DateField(default=datetime.date(2017, 5, 16))),
                ('address', models.CharField(max_length=500)),
                ('lastStatusChanged', models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 45, 47, 147851))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 45, 47, 147851))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('signUpDate', models.DateField(default=datetime.date(2017, 5, 16))),
                ('activeUser', models.BooleanField(default=False)),
                ('inactiveSince', models.DateField(default=datetime.date(2017, 5, 16))),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.City')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('signUpDate', models.DateField(default=datetime.date(2017, 5, 16))),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Thana')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='thanaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Thana'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Thana'),
        ),
        migrations.AddField(
            model_name='device',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
