# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceStatus', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 50, 1, 684993))),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='lastStatusChanged',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 50, 1, 669367)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 50, 1, 669367)),
        ),
        migrations.AddField(
            model_name='datalog',
            name='deviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Device'),
        ),
    ]
